#include "stm32f1xx_hal.h"

#include "config.h"

void Device_Power3V3Open() {
    HAL_GPIO_WritePin(POWER3V3_GPIO_PORT, POWER3V3_PIN, GPIO_PIN_SET);
}

void Device_Power3V3Close() {
    HAL_GPIO_WritePin(POWER3V3_GPIO_PORT, POWER3V3_PIN, GPIO_PIN_RESET);
}

void Device_Power5VOpen() {
    HAL_GPIO_WritePin(POWER5V_GPIO_PORT, POWER5V_PIN, GPIO_PIN_SET);
}

void Device_Power5VClose() {
    HAL_GPIO_WritePin(POWER5V_GPIO_PORT, POWER5V_PIN, GPIO_PIN_RESET);
}

void Device_LaserOpen() {
    HAL_GPIO_WritePin(LASER_GPIO_PORT, LASER_PIN, GPIO_PIN_SET);
}

void Device_LaserClose() {
    HAL_GPIO_WritePin(LASER_GPIO_PORT, LASER_PIN, GPIO_PIN_RESET);
}

void Device_DatalightOpen() {
    HAL_GPIO_WritePin(DATALIGHT_GPIO_PORT, DATALIGHT_PIN, GPIO_PIN_SET);
}

void Device_DatalightClose() {
    HAL_GPIO_WritePin(DATALIGHT_GPIO_PORT, DATALIGHT_PIN, GPIO_PIN_RESET);
}

void Device_StatusBlueLEDOpen() {
    HAL_GPIO_WritePin(STATUS_BLUE_LED_GPIO_PORT, STATUS_BLUE_LED_PIN, GPIO_PIN_SET);
    HAL_GPIO_WritePin(STATUS_RED_LED_GPIO_PORT, STATUS_RED_LED_PIN, GPIO_PIN_RESET);
}

void Device_StatusRedLEDOpen() {
    HAL_GPIO_WritePin(STATUS_BLUE_LED_GPIO_PORT, STATUS_BLUE_LED_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(STATUS_RED_LED_GPIO_PORT, STATUS_RED_LED_PIN, GPIO_PIN_SET);
}

void Device_StatusLEDClose() {
    HAL_GPIO_WritePin(STATUS_RED_LED_GPIO_PORT, STATUS_RED_LED_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(STATUS_BLUE_LED_GPIO_PORT, STATUS_BLUE_LED_PIN, GPIO_PIN_RESET);
}
